### ISSUE TITLE
Approval workflow for timesheets - Settings Error

### ISSUE THREAD

**Issue by rupeshkumar1992** [KatjaGlassConsulting/ApprovalBundle#1]
Hi,

I have added Approval workflow for timesheets/Hours Approval plugin with this plugin already added 
Now, i am trying to setup hours approval plugin , but i am not able to do it.
I Don't known how to set settings for this, please provide me support for this.

Can you please solve this my issue, I am not Getting option of approve and reject.
In below screenshot shows Setting are not configured yet, when i am trying to configure settings its showing empty data.
can you please, tell me how to solve this.

Screenshot:
![image](https://user-images.githubusercontent.com/112627535/188610807-209d01cf-0556-4a65-ba60-299d1223fdfc.png)

**Comment by KatjaGlassConsulting** [comment]
Hi, thanks for this issues. The documentation about settings had been missing. I included those now: https://github.com/KatjaGlassConsulting/ApprovalBundle/blob/main/README.md/#settings

Please check and try out. If additional information is missing, please let me know, then I can enhance the documentation further.
