### ISSUE TITLE
Total vs Expected Duration

### ISSUE THREAD

**Issue by asaglam76** [KatjaGlassConsulting/ApprovalBundle#10]
weekly working hours
Mo-Do 8h
Fr: 7h
Total 39h.

Total Duration is 39h but why expected duration is showing 46h. It looks like that somehow weekends also calculated. We use also the vacation / sick day and controlling plugin
![hours_approval](https://user-images.githubusercontent.com/46278841/212656395-7c8594d5-f5cf-4ecf-b76c-237bfd124fc4.PNG)
![grafik](https://user-images.githubusercontent.com/46278841/212657372-12ac9712-538f-4616-89f8-9a60eed908a2.png)

![grafik](https://user-images.githubusercontent.com/46278841/212656976-e43044ee-5b13-40f3-9bd7-ed342ef998a4.png)

![grafik](https://user-images.githubusercontent.com/46278841/212657256-bd787b8d-43b9-47f5-94ce-367c9a453dea.png)

**Comment by KatjaGlassConsulting** [comment]
Hi, the expected working hours are based on the user setting for the workdays. These you can see under "user" -> select the specific user and go to the working hours per day settings summing up Monday-Sunday. Typically Saturday and Sunday are set to 0.

![image](https://user-images.githubusercontent.com/55694577/212660477-2bf5e439-86d8-4b07-add9-85f6fd6ee337.png)

**Comment by asaglam76** [comment]
Hi, thats right .. sat and sun is set to 0 .. see
![grafik](https://user-images.githubusercontent.com/46278841/212669918-b87cba61-6614-4de0-9fc3-20b06ee93951.png)
thats why I'm wondering :)

**Comment by KatjaGlassConsulting** [comment]
Did you change the values for this person? The "expected duration" is calculated and stored when the first "submit for approval" is done. You can also check in the database the corresponding entry. If you find that one, you can apply "/60/60" to get the minutes - this is 46hours according your screenshot. When you scroll to an unsubmitted week (e.g. week 10 this year), is the expected duration is also 46 or is this in that case 39?

![image](https://user-images.githubusercontent.com/55694577/212703681-282e1cec-9535-475e-a588-bdd18856dbcf.png)

**Comment by asaglam76** [comment]
Beginning is as of 2023 .. we've newly implemented Kimai. 
![grafik](https://user-images.githubusercontent.com/46278841/212713037-6da48945-7e6b-4bce-a20a-d9665f4fe8bc.png)
![grafik](https://user-images.githubusercontent.com/46278841/212713523-93149877-a7d4-4daa-b026-e694e5b46f7a.png)
For me it looks like that it is expecting for every day 1h >> 39h + 7h = 46h .. I also wonder if it has something to do with the break-time ... see above .. for 8h it is separated in two timebands (for example 08:00-12:00 and 13:00-17:00) but in your screenshots it looks like that you entering full 8h without any breaks. The fact that there is a discrepancy between Total and Expected is currently not a big issue ... On the part of the employees and the granting persons, there are then questions as to where the discrepancy comes from. One employee complained to me personally today why she was expected to work 46 hours. 🤣
