### ISSUE TITLE
Times editable after approval

### ISSUE THREAD

**Issue by levino** [KatjaGlassConsulting/ApprovalBundle#11]
Hi there, thanks for the great plugin!

I just approved a task of 4 hours length for a member of a team as the team leader and then changed the tracked time to 3 hours as the team member. I would think that either the team member should not be able to change approved items any more (probably they should be locked for edit once they are submitted for approval) or the approval should be removed ones the entry has been changed. Please advise.

**Comment by KatjaGlassConsulting** [comment]
You must have installed the LockdownPerUser plugin to have this lockdown functionality.
It's explained a bit here: https://github.com/KatjaGlassConsulting/ApprovalBundle#functionality-of-lockdown
So what you expect should be the case.

Make sure that according your user-settings lockdown periods cannot be modified by user/team-lead:
lockdown_grace_timesheet
lockdown_override_timesheet

The ApprovalBundle Plugin sets the lock dates for that user to the end-of-the-locked week. You can see it via User -> select the one -> Settings at the bottom:

![image](https://user-images.githubusercontent.com/55694577/213983443-4f4debb1-f37a-40cf-bae8-1f89b9f42460.png)

**Comment by levino** [comment]
I installed the plugin and guess this fixes the issue. Will reopen if issue persists. Thank you.
