### ISSUE TITLE
Can not have access to terminal

### ISSUE THREAD

**Issue by andalepaco** [KatjaGlassConsulting/ApprovalBundle#15]
No posible run the command "bin/console kimai:bundle:approval:install".
¿Its posible import the tables from phpmyadmin to enable plugin?

**Comment by KatjaGlassConsulting** [comment]
What is the corresponding error message? It's the usual way how Kimai Plugins are installed. You might need to prefix "php" in case that's not setup as default, e.g. "php bin/console kimai:bundle:approval:install"

**Comment by KatjaGlassConsulting** [comment]
Closed as no follow-up.

**Comment by andalepaco** [comment]
If you do not have access to Termina and only have access to cpanel, you think you can run the command from cron
