### ISSUE TITLE
Kimai v2 support

### ISSUE THREAD

**Issue by designermonkey** [KatjaGlassConsulting/ApprovalBundle#17]
Hello there! Are there any plan to support Kimai v2?

**Comment by KatjaGlassConsulting** [comment]
Hi, I have it on the radar, but think it might only come in Q4. Due to other priorities, I expect we switch to v2 somewhen next year.

**Comment by pxlwrk** [comment]
Would love to use it with Kimai2!

**Comment by KatjaGlassConsulting** [comment]
Dear all,
we have decided not to switch to Kimai 2, and for this I do not plan any updates in the near future. 

I created a new branch, so if someone has resources to update to Kimai version 2, I am happy to accept pull requests. You can also feel free to clone this repository and do updates elsewhere. I can include a link then.

**Comment by pboissonneault** [comment]
What are the main difference between Kimai2 v1.x and v2 that prevent this plugin to be updated ?
I might have time later this year to look at this.

**Comment by KatjaGlassConsulting** [comment]
Hi, the updates requires according the block quite some changes: https://www.kimai.org/documentation/migration-v2.html

As my core customer has decided not to change to kimaiV2, I did not plan for the update myself, but would be happy if you could support. 

One of the changes is the license with changed from MIT to GPLv3 which makes it different when code for a plugin is copied from the core tool.

**Comment by pboissonneault** [comment]
Thanks, I'll look at that send pull requests if it works, but from what I understand you won't update your plugin if you keep using Kimai2 v1.x ?

**Comment by KatjaGlassConsulting** [comment]
I will test whether it runs on both and I will maintain a second branch for v2.

**Comment by KatjaGlassConsulting** [comment]
Work is ongoing. Many thanks to Vitor. The branch is `kimai_v2_update`.

**Comment by KatjaGlassConsulting** [comment]
Thanks also to @sammaclennan for working on this issue as well. It's still buggy, but gets better and better.

**Comment by vitormattos** [comment]
Hi @KatjaGlassConsulting 

Could you list the pending points to finish this issue? Maybe will help to receive contributions from other developers.

**Comment by KatjaGlassConsulting** [comment]
Hi @vitormattos, Kevin did directly a new PR to support the new kimai version. This PR will likely be merged soon. Can you probably already test that? Unluckily he didn't see the kimai_v2_update branch. Maybe I will also switch the main to Kimai v2 support and a new kimai_v1 branch. 

Thanks to your support already and have great vacation days!

**Comment by vitormattos** [comment]
A best way to prevent this is to create a new branch from main called: `stable1`

Because `stable1`?
- Will be the version of this app that will maintain compatible with Kimai v1 and only will receive cherry picks from main branchi

And maintain the branch main compatible to newest version of Kimai.

Every when launch a new big version of Kimai that break the Approval, we will need to create the next stable branch from main.

**Comment by KatjaGlassConsulting** [comment]
Thanks to all the supporter - version 2 support is now available on the `main` branch with the current Release as version 2.0.0. The version 1 support is available on the `bundle_for_kimai_v1` branch with the current Release as version 1.0.0.
