### ISSUE TITLE
500 error at endponint /api/next-week

### ISSUE THREAD

**Issue by vitormattos** [KatjaGlassConsulting/ApprovalBundle#21]
> I am getting 500 errors ... I am checking with the API component from the demo bundle ... that is working, but not the APIs from the approval bundle.
> 
> ![image](https://github.com/KatjaGlassConsulting/ApprovalBundle/assets/55694577/eae93a6e-533d-4e57-80c0-d616739975bf)
> 
_Originally posted by @KatjaGlassConsulting in https://github.com/KatjaGlassConsulting/ApprovalBundle/issues/20#issuecomment-1838806418_

**Comment by vitormattos** [comment]
Maybe related with:

> This has to do with the parameter - looking into ApprovalNextWeekApiController.php:
> 
> When I remove the parameter definition it's working: #[OA\Parameter( name: 'user', in: 'query', type: 'integer', description: 'User ID to get information for', required: false, )]
> 
> ```
> public function nextWeekAction(Request $request): Response
> ```
> 
> So I guess it must be defined differently.

Originally posted by @KatjaGlassConsulting in https://github.com/KatjaGlassConsulting/ApprovalBundle/pull/20#issuecomment-1838823070

**Comment by KatjaGlassConsulting** [comment]
API is now working - need to perform final tests tomorrow
