### ISSUE TITLE
Tag names

### ISSUE THREAD

**Issue by kevinpapst** [KatjaGlassConsulting/ApprovalBundle#31]
Hi Katja,  

one request - not regarding the code: is there a reason you started adding the `v` to the tag names?

In the past the tag names only included the version itself.

<img width="237" alt="Bildschirmfoto 2024-01-12 um 13 04 38" src="https://github.com/KatjaGlassConsulting/ApprovalBundle/assets/533162/a667eecc-dd98-4a4e-a287-4417af37e62e">

If you prefer the `v`, you could call the release v1.0.1 and the tag 1.0.1 ?

I stumbled upon it, while writing a bash script that use the versions from the store page, which don't mention the `v`:

<img width="549" alt="Bildschirmfoto 2024-01-12 um 13 22 50" src="https://github.com/KatjaGlassConsulting/ApprovalBundle/assets/533162/f7a37070-1c15-4e70-ad87-993822f06eef">

**Comment by KatjaGlassConsulting** [comment]
I will re-label it to without the v to support your bash script. There are just too many ways we can do things. No reason for this. It should be done by Monday at least.

**Comment by kevinpapst** [comment]
Don't change existing stuff, re-creating tags can cause weird issues.
My wish was just for future 😄 

Any yes, sometimes less options would be desirable.

**Comment by kevinpapst** [comment]
Closing, thanks Katja!

**Comment by KatjaGlassConsulting** [comment]
ok, so only for future releases I will work with no "v" tags and names.
