### ISSUE TITLE
V2 - 2 new options - Teamlead self approve & System-Admin include

### ISSUE THREAD

**Issue by KatjaGlassConsulting** [KatjaGlassConsulting/ApprovalBundle#32]
Two new features has been implemented in version 1 to support two new options. 
- new option to allow system-administrators to be included in approvals
- new option to allow teamlead to self-approve the own weeks

It's in the branch `feature/v1_add_options` the commits are 3f788376d4a973bbca9abc907c155c9be148742e and 3405e40cc03241bc705cc0fc98e81302f190b0c9

@vitormattos, would that be something for you?

**Comment by sammaclennan** [comment]
@KatjaGlassConsulting I'll be migrating these features across to v2 this week.

**Comment by kevinpapst** [comment]
Add me as reviewer to the PR please

**Comment by KatjaGlassConsulting** [comment]
Thanks @sammaclennan, the functionality is now also included into version for Kimai 2.
