### ISSUE TITLE
Approval without duration

### ISSUE THREAD

**Issue by kevinpapst** [KatjaGlassConsulting/ApprovalBundle#4]
Would it be possible to add a mode where you do not have to specify the daily working times?

I am sure you have valid reasons in your use-case.
But I see many scenarios, where you want to approve / reject times without the necessity of checking daily working times.

Times change and working contracts do not require to have such a setup nowadays 😁

**Comment by KatjaGlassConsulting** [comment]
Hi Kevin,

thanks for this feature request. This would make the plugin more generic, you are right. I will keep it as active issue open. But I will currently not be working on this - likely not this year.
