### ISSUE TITLE
"To Approve" tab needs white font color for dark theme

### ISSUE THREAD

**Issue by brmeyer** [KatjaGlassConsulting/ApprovalBundle#41]
Thank you for everything you do! We love Kimai!

I'm starting to experiment with this plugin and noticed the To Approve tab's data table doesn't appear to update for dark mode. The text is there (I'm highlighting one row). Is it a simple update to switch it to the white font? Happy to help with a contribution...

![image](https://github.com/KatjaGlassConsulting/ApprovalBundle/assets/812741/d615d0fe-02a5-4223-a5c7-ec3dc0577852)

**Comment by brmeyer** [comment]
https://github.com/KatjaGlassConsulting/ApprovalBundle/pull/42 seems to fix it, simply removing the default `bg-dark-lt` from the `status_color_class` macro. Looks correct in Bright mode as well?

**Comment by KatjaGlassConsulting** [comment]
Thanks for the update, yes it's then working for dark and light theme. It will be merged soon.

**Comment by KatjaGlassConsulting** [comment]
Released in 2.0.4
