### ISSUE TITLE
[Bug] Link in email doesn't work

### ISSUE THREAD

**Issue by kevinpapst** [KatjaGlassConsulting/ApprovalBundle#43]
Some emails (here at least the status change email for a rejected week) contain absolute path URLs, which the cannot be clicked. 

See:
https://github.com/KatjaGlassConsulting/ApprovalBundle/blob/main/Repository/ApprovalRepository.php#L710-L714

We need to replace `UrlGeneratorInterface::ABSOLUTE_PATH` with `UrlGeneratorInterface::ABSOLUTE_PATH`.

Who is willing to ship a PR to fix it?

**Comment by KatjaGlassConsulting** [comment]
Hi Kevin, 
the replacement is the same? Is there another value to use than `UrlGeneratorInterface::ABSOLUTE_PATH`?

**Comment by kevinpapst** [comment]
Hahaha, copy & paste... :blush:

- `ABSOLUTE_PATH` should create something like `/de/approval` while 
- `ABSOLUTE_URL` should create something like `https://www.example.com/de/approval`

Maybe you can try it, I am in the middle of a feature branch, which I can't switch, so I can't test right now.

**Comment by KatjaGlassConsulting** [comment]
:) I will give it a try and update. :) Thanks

**Comment by KatjaGlassConsulting** [comment]
Corrected and released as 2.0.4
