### ISSUE TITLE
Email Notification on Submission, Approval/Rejection of Weekly Timesheet

### ISSUE THREAD

**Issue by vikasgunjeti** [KatjaGlassConsulting/ApprovalBundle#45]
Hi Team, 

All functionalities are working correctly, however, users are not getting email notifications after submission, approval/rejection of the weekly timesheet. How to achieve this functionality.

Thank you,
Vikas

**Comment by KatjaGlassConsulting** [comment]
Hi Vikas,

Have setup Kimai to send mails? So the .env variable is accordingly set and did you try that receiving other mails from Kimai in general works? This is described here: https://www.kimai.org/documentation/emails.html.

**Comment by vikasgunjeti** [comment]
Hi Team,

I followed the above documentation. Email notifications are properly working now. Thank you for your quick support on this.

Thank You,
Vikas
