### ISSUE TITLE
user can't show deny approval reason

### ISSUE THREAD

**Issue by wsl222000** [KatjaGlassConsulting/ApprovalBundle#49]
user can't show deny approval reason from history
![image](https://github.com/KatjaGlassConsulting/ApprovalBundle/assets/7600000/4839f20e-4763-4291-a50c-99d7c0e2c4d3)

**Comment by KatjaGlassConsulting** [comment]
There had been a bug. Can you test the fix for kimai2? It is in SHA: afa0c0195a360b94f05f80e6419b949e1eed1e72 .
For kimai1 it is tested and in SHA: 5b227fd0c7075e132bff87b7bef5129bcbbdd56a
