### ISSUE TITLE
How to translate this plugin?

### ISSUE THREAD

**Issue by ldmpub** [KatjaGlassConsulting/ApprovalBundle#52]
Hi,

This Kimai extension seems to be translatable 👍.

Is there any translation how to? Which explains translation workflow and tools to be used to proceed ?
_(I want to help create the french translation but I have limited knowledge of xlf files / XLIFF format)_

**First step**
- [ ] **Can you please add the needed french [fr] translation file(s) to the project?** (3 translations - de, en, hr - are yet available for this Kimai extension, see [katjaglass-approval-bundle.html](https://github.com/KatjaGlassConsulting/ApprovalBundle/tree/main/Resources/translations))

>  [!NOTE]
> Original [discussion in Kimai projet](https://github.com/kimai/kimai/discussions/4982)

**Comment by KatjaGlassConsulting** [comment]
Hi @ldmpub,

you can copy ApprovalBundle\Resources\translations\messages.en.xliff to messages.fr.xliff and rename all texts which are in between <target> and </target>. If you do the translations, please create a pull request, then this new french translation can be included into the bundle as well. As soon as I have a translation file, I will do all following changes considering that language.

When you create the translation file, you need to refresh Kimai so the new tranlations are loaded:

```
bin/console kimai:reload -n
bin/console cache:clear
```

**Comment by ldmpub** [comment]
Ok, it's clear, let's go 😀.

**Comment by ldmpub** [comment]
Hi, I won't translate this addon to french as far as I will not use it anymore.
