### ISSUE TITLE
Timesheet rejection Email Says "Approved" if no reason is provided

### ISSUE THREAD

**Issue by duyanhtruong** [KatjaGlassConsulting/ApprovalBundle#54]
The email logic in [Resources/views/approvedChangeStatus.email.twig](https://github.com/KatjaGlassConsulting/ApprovalBundle/blob/main/Resources/views/approvedChangeStatus.email.twig) has a small issue: If the timesheet is rejected but the approver leaves the reason blank, then an email like this will be sent:

![image](https://github.com/user-attachments/assets/66eaa501-4161-4c16-b1fb-9be538fd055e)

The title says "rejected" but the message still says "approved"

**Proposed solution:**
I modified the logic in approvedChangeStatus.email.twig to be:

```
{% block report %}
    {% if reason is not null %}
        <p>{{ 'email.hello' | trans }} {{ submitter }},</p>
        {% if reason != '' %}
            <p>{{ approver }} {{ 'email.reject.message' | trans }} {{ week }}</p>
            <p>{{ 'email.reason' | trans }} {{ reason }}</p>
        {% else %}
            <p>{{ approver }} {{ 'email.reject.message' | trans }} {{ week }}</p>
        {% endif %}
        <a href="{{ url }}">{{ week }}</a>
    {% else %}
        <p>{{ 'email.hello' | trans }} {{ submitter }},</p>
        <p>{{ approver }} {{ 'email.approved.message' | trans }} {{ week }}</p>
        <a href="{{ url }}">{{ week }}</a>
    {% endif %}
{% endblock %}
```

The above logic seems to fix this bug

**Comment by KatjaGlassConsulting** [comment]
Thanks for this hint, I will implement this soon.
