### ISSUE TITLE
Error Encountered While Running Cron Job for Teamleader and admin Command

### ISSUE THREAD

**Issue by subash-s23** [KatjaGlassConsulting/ApprovalBundle#55]
Hi, 
I am trying to run the cron job commands for both admin and team leader

php /var/www/html/kimai/bin/console kimai:bundle:approval:admin-not-submitted-users 
php /var/www/html/kimai/bin/console kimai:bundle:approval:teamlead-not-submitted-last-week

Error are mentioned below
Versions;
PHP 8.1.29 (cli) (built: Jun  6 2024 16:52:57)
[Timesheet approvals] A Kimai plugin to manage approvals and supporting related API Version 2.0.7

09:10:02 CRITICAL  [console] Error thrown while running command "kimai:bundle:approval:teamlead-not-submitted-last-week". Message: "[Syntax Error] line 0, col 96: Error: Expected Literal, got ')'" ["exception" => Doctrine\ORM\Query\QueryException { …},"command" => "kimai:bundle:approval:teamlead-not-submitted-last-week","message" => "[Syntax Error] line 0, col 96: Error: Expected Literal, got ')'"] ["channel" => "console"]

In QueryException.php line 34:
                                                                   
  [Syntax Error] line 0, col 96: Error: Expected Literal, got ')'  
                                                                   
In QueryException.php line 23:
                                                                               
  SELECT ap FROM KimaiPlugin\ApprovalBundle\Entity\Approval ap INNER JOIN ap.  
  user u WHERE u.id IN() AND ap.startDate >= :begin GROUP BY ap ORDER BY ap.s  
  tartDate ASC, u.username ASC, ap.creationDate ASC                            
                                                                               
kimai:bundle:approval:teamlead-not-submitted-last-week

**Comment by KatjaGlassConsulting** [comment]
I guess this issue is still available and you are using kimai2? I am not running with a mail server for testing and my production system is still running with kimai 1 for this it's difficult. It looks strange that there is no user id: u.id IN()

**Comment by kevinpapst** [comment]
@KatjaGlassConsulting this method can return an empty array:
https://github.com/KatjaGlassConsulting/ApprovalBundle/blob/main/Command/TeamleadNotSubmittedCommand.php#L52

You have several calls in the repository where you use an array for `>in()`, these will fail if the array of users is empty, e.g. here: https://github.com/KatjaGlassConsulting/ApprovalBundle/blob/main/Repository/ApprovalRepository.php#L716

Maybe guard the outside loop in the command with a count() > 1.

**Comment by KatjaGlassConsulting** [comment]
@subash-s23 - can you please check the changes here: https://github.com/KatjaGlassConsulting/ApprovalBundle/tree/feature/fix_null_array_issue55 

I don't have a test setup for this case.
