### ISSUE TITLE
Feature request: Re-approve for multiple activity in same week

### ISSUE THREAD

**Issue by mpermperpisang** [KatjaGlassConsulting/ApprovalBundle#58]
Hi
First I want to say thank you so much for this awesome plugin
It really helps me to manage my freelancers

The thing is when i testing with conditions like this:
Next week number is 41 with range date is 7 - 11 (mon - fri)
I input Annual Leave for 8th august
Then the manager approve
Next i input on Sick Leave for 9th august
But i cannot re-request the approval to the manager, and it auto show new activity to same week that already approved by the manager

The expectation is, the manager want to ack-ed & re-approved every new input of all activity in the same week

Will it be possible to re-submit new approval for the same week?
This icon should re-appear when there is any new activity submit on the same week
<img width="129" alt="Screenshot 2024-10-03 at 12 31 57" src="https://github.com/user-attachments/assets/6693d8ef-77a4-4626-bba7-fb7f7e2e2b99">

Thank you :)

**Comment by KatjaGlassConsulting** [comment]
Hi @mpermperpisang ,

it's recommended to use the "LockdownBundle" as well. Then it's not possible to create additional timesheet entries. New timesheet entries are then only possible when the approval is already canceled for that week. I have to admit I don't know how the vacation and sick leave bundle works in Kimai2. Are you using LockdownBundle and do you have such issues only with vacation/sick-leave or also with "normal" timesheet entries?

**Comment by mpermperpisang** [comment]
i not installed https://github.com/Keleo/LockdownPerUserBundle yet
lemme try that first

the issue for me is also when im trying "normal" timesheet entries

**Comment by KatjaGlassConsulting** [comment]
Does this solve your issue?

**Comment by mpermperpisang** [comment]
yeah its fine
thanks for the suggestion
i'll closed this issue
