### ISSUE TITLE
ApprovalBundle sent an invalid submitted url

### ISSUE THREAD

**Issue by pylearn2030** [KatjaGlassConsulting/ApprovalBundle#59]
Dear,
I am using ApprovalBundle plugin to approve the timesheets but I got the approval emails with message

"The page you were on is trying to send you to an invalid URL (http:///en/approval/week_by_user?user=2&date=2024-02-2).
If you do not want to visit that page, you can return to the previous page"

How to correct this url? Please help!
Thank you for your help!
Py.

**Comment by KatjaGlassConsulting** [comment]
Hi, did you set the mail url settings for the plugin?

**Comment by pylearn2030** [comment]
Hi, I didn't. How can I do this?

**Comment by KatjaGlassConsulting** [comment]
welcome
