### ISSUE TITLE
TypeError in WeekReportController Class

### ISSUE THREAD

**Issue by YouSimone** [KatjaGlassConsulting/ApprovalBundle#60]
I encountered a TypeError in the WeekReportController class of the ApprovalBundle package. The error occurs when trying to instantiate a DateTime object using another DateTime instance as an argument.

This is the error: 
CRITICAL: Uncaught PHP Exception TypeError: "DateTime::__construct(): Argument #1 ($datetime) must be of type string, DateTime given" at WeekReportController.php line 133

The error occurs on the following line of code:
'week' => $this->formatting->parseDate(new DateTime($startWeek)),

If $startWeek is already a DateTime object, passing it again to the DateTime constructor causes an error. This leads to a situation where the application fails to function correctly

It is advisable to check if $startWeek is already a DateTime object before passing it to the constructor. Here’s how the code could be modified:
'week' => $this->formatting->parseDate($startWeek instanceof DateTime ? $startWeek : new DateTime($startWeek)),

I hope this information is helpful for resolving the issue for anyone else who has encountered the same error.

Environment:

PHP Version: 8.3
Symfony Version: 6

**Comment by kevinpapst** [comment]
Thanks! Want to create a PR to fix that?

**Comment by YouSimone** [comment]
Sure! I have already submitted it.

**Comment by KatjaGlassConsulting** [comment]
Thanks for the PR, a monthly approval is not planned from my end, but I accept PRs. I would expect a separate monthly plugin might be easier which could be based on this plugin, though.

**Comment by YouSimone** [comment]
Ok sure! Thanks
