### ISSUE TITLE
Error 500 - getWorkingTimeForDate return vale must be type int, none returned

### ISSUE THREAD

**Issue by empx92** [KatjaGlassConsulting/ApprovalBundle#64]
Hi,
after adding the Workinghours in a Userprofile i get an error when clicking on the "Approval" Link in the mainmenu.

It is a Freshinstall with Kimai 2.24.0 for testing purposes.

The log says:

```
[request] CRITICAL: Uncaught PHP Exception TypeError: "KimaiPlugin\ApprovalBundle\Settings\MetaFieldSettings::getWorkingTimeForDate(): 
Return value must be of type int, none returned" at MetaFieldSettings.php line 40 {"exception":"[object] (TypeError(code: 0): KimaiPlugin\\ApprovalBundle\\Settings\\MetaFieldSettings::getWorkingTimeForDate(): 
Return value must be of type int, none returned at /data/web/****/html/****/kimai/var/plugins/ApprovalBundle/Settings/MetaFieldSettings.php:40)"} []
```

Which is related to that line (40):
```
public function getWorkingTimeForDate(User $user, \DateTimeInterface $dateTime): int
    {
        $this->workingTimeService->getContractMode($user)->getCalculator($user)->getWorkHoursForDay($dateTime);
    }
```

Additional Info:
There are no working hours until 21.11.2024 for that the "Working Contract" says -176:00 for the previous weeks, i don't know if that can be set to the registration date of the user which would be the correct behavior.

**Comment by kevinpapst** [comment]
Share a screenshot of your settings for that user please

**Comment by empx92** [comment]
![image](https://github.com/user-attachments/assets/da366d0a-4fab-4d5b-8e3f-09e46deb52bd)
And as in desc.:
![image](https://github.com/user-attachments/assets/19141c9c-bd34-401e-9a3b-f70596269d10)

**Comment by kevinpapst** [comment]
Weird. Can you check if setting 0:01 for saturday and sunday fixes it?
If so, revert to 0:00 => what happens now.

**Comment by empx92** [comment]
No Sadly that doesn't do the trick.
I currently try to fill up the months with time, to see what happens

**Comment by kevinpapst** [comment]
Ah, I found the issue. There is a return statement missing. I wonder why nobody hit that bug before... See #65

**Comment by empx92** [comment]
Thanks, just tried the change and everything is working now ;)
